### ISSUE TITLE
ATL Server going down with CodePlex

### ISSUE THREAD

**Issue by gabegundy** [google/omaha#108]
Just a heads up, the [atlserver](http://atlserver.codeplex.com/) project is going down with [CodePlex](https://blogs.msdn.microsoft.com/bharry/2017/03/31/shutting-down-codeplex/).

I've posted it on GitHub, but not without issues. Feel free to read about [them](https://github.com/gabegundy/atlserver).

With luck the code will be properly migrated, but I don't have much hope that it will.

**Comment by macqm** [comment]
It seems that the only header from atlserver that Omaha uses is `atlrx.h` and it should be fairly easy to replace that with STL's <regex>.

I looked into this and learned that:
* regex doesn't seem to have exception safe overloads, so providing an incorrect regex string will crash the app, but it looks like Omaha uses only constant regex strings, not user provided (with the exception of the site lock pattern that can be overridden with the OmahaDev regkey).
* the syntax used by ATL and STL for expressing regex is different
* the methods map pretty well (e.g. `AtlRE::PartialMatch` to `std::regex_search`, `RE::FullMatch` and `std::regex_match`).

**Comment by macqm** [comment]
@sorinj: Sounds like this is fixed with https://github.com/google/omaha/commit/d68de964049b2abdb4814ba1884cf882eb53a359

**Comment by sorinj** [comment]
Indeed, hopefully, we did not break something with the new regexes.
