### ISSUE TITLE
Omaha Will Not Build

### ISSUE THREAD

**Issue by AMartens181** [google/omaha#111]
`scons: warning: No installed VCs
File "C:\swtoolkit\site_scons\site_init.py", line 426, in SiteInitMain

scons: warning: No version of Visual Studio compiler found - C/C++ compilers most likely not set correctly
File "C:\swtoolkit\site_scons\site_init.py", line 426, in SiteInitMain
scons: Reading SConscript files ...

scons: warning: No installed VCs
File "C:\swtoolkit\site_scons\site_tools\target_platform_windows.py", line 283, in generate

scons: warning: No version of Visual Studio compiler found - C/C++ compilers most likely not set correctly
File "C:\swtoolkit\site_scons\site_tools\target_platform_windows.py", line 283, in generate
TypeError: cannot concatenate 'str' and 'NoneType' objects:
  File "C:\Users\user\Desktop\OMAHADEV\omaha\main.scons", line 154:
    SIGNTOOL = _signtool_path,
  File "C:\Python24\Lib\site-packages\scons-1.3.1\SCons\Environment.py", line 1003:
    apply_tools(self, tools, toolpath)
  File "C:\Python24\Lib\site-packages\scons-1.3.1\SCons\Environment.py", line 107:
    env.Tool(tool)
  File "C:\Python24\Lib\site-packages\scons-1.3.1\SCons\Environment.py", line 1709:
    tool(self)
  File "C:\Python24\Lib\site-packages\scons-1.3.1\SCons\Tool\__init__.py", line 181:
    apply(self.generate, ( env, ) + args, kw)
  File "C:\Users\user\Desktop\OMAHADEV\omaha-master\omaha\site_scons\site_tools\windows_vc14_0.py", line 121:
    None
  File "C:\Users\user\Desktop\OMAHADEV\omaha-master\omaha\site_scons\site_tools\windows_vc14_0.py", line 57:
    None`
Visual Studio 2017

**Comment by SulfredLee** [comment]
I have the same problem, is there any solution?
Following is what I have done.
    - I followed [Developer Setup Guide](https://github.com/google/omaha/blob/master/doc/DeveloperSetupGuide.md)
    - Open a fresh cmd.exe window as Administrator.
    - Navigate to the 'omaha' directory in your source checkout
    - Run the vsvars.bat file by "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"
    - hammer.bat
Then I received the above errors.

I also tried:
    - Open a fresh "Developer Command Prompt for VS2015.exe" window as Administrator.
    - Navigate to the 'omaha' directory in your source checkout
    - Run the vsvars.bat file by "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"
    - hammer.bat
Then I received the above errors again.

**Comment by AMartens181** [comment]
Running hammer.bat from the developer command prompt instead of from a regular cmd eliminates the need to run vcvarsall each time.

I had to add a few more locations for visual studio to my PATH

If you get `"fatal error C1083: Cannot open include file: 'bits10_1.h': No such file or directory" when including bits.h in your project.`, go to line 824 of bits5_0.h and comment out the following:  #include "bits10_1.h"

**Comment by Lidanha** [comment]
Did anyone find a solution to this yet?

**Comment by AMartens181** [comment]
@Lidanha 
This is what my hammer.bat looks like. Everything is environmental variables because it's easier
```batch
@echo off
:: "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
:: setx VisualStudioVersion 14.0 /m
REM call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\vsvars32.bat"
REM call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
REM cd C:\Users\user\Desktop\OMAHADEV\omaha

REM set OMAHADEV=%LOCALPROFILE%\Desktop\OMAHADEV
set OMAHA_PSEXEC_DIR=%OMAHADEV%\third_party

setlocal

rem -- Set all environment variables used by Hammer and Omaha. --

:: VS2003/VC71 is 1310 (not supported by the current build).
:: VS2005/VC80 is 1400 (not supported by the current build).
:: VS2008/VC90 is 1500 (not supported by the current build).
:: VS2010/VC10 is 1600 (not supported by the current build).
:: VS2012/VC11 is 1700 (not supported by the current build).
:: VS2013/VC12 is 1800.
:: VS2015/VC14 is 1900.
:: VS2017/VC14.1 is 1911.

if "%VisualStudioVersion%"=="" goto error_no_vc
if "%VisualStudioVersion%"=="12.0" goto vc120
if "%VisualStudioVersion%"=="14.0" goto vc140
::goto error_vc_not_supported

:vc120
set OMAHA_MSC_VER=1800
goto set_env_variables

:vc140
set OMAHA_MSC_VER=1900
goto set_env_variables

REM :vc140
REM set OMAHA_MSC_VER=1911
REM goto set_env_variables

:set_env_variables

:: Change these variables to match the local build environment.

:: Directory where the Go programming language toolchain is installed.
set GOROOT=%GOROOT%

:: Directory where AtlServer files are.
set OMAHA_ATL_SERVER_DIR=%OMAHADEV%\third_party\ATL

:: This will depend on your OS. If this version of the .Net framework came with
:: the OS, then set it to the framework directory
:: (something like C:\Windows\Microsoft.NET\Framework\v2.0.50727).
:: Otherwise, set it to the directory where the .NET framework is installed.
set OMAHA_NET_DIR=%WINDIR%\Microsoft.NET\Framework\v2.0.50727

:: This directory is needed to find mage.exe tool, which is the .Net manifest
:: generating tool. This tool ships as part of the Windows SDK.
:: However, newer versions of mage.exe can't targer older versions of .Net
:: framework. If there is a need for the click-once application to run on older
:: versions of the .Net framework, then an older version of the Windows SDK
:: needs to be installed and this environment variable point to that directory.
set OMAHA_NETFX_TOOLS_DIR=%WindowsSDK_ExecutablePath_x86%

:: Directory where Python (python.exe) is installed.
set OMAHA_PYTHON_DIR=C:\Python24

:: Directory in WiX where candle.exe and light.exe are installed.
set OMAHA_WIX_DIR=%WIX%\bin

:: Root directory of the WTL installation.
set OMAHA_WTL_DIR=%OMAHADEV%\third_party\WTL

set OMAHA_PLATFORM_SDK_DIR=%WindowsSdkDir%\
set OMAHA_WINDOWS_SDK_10_0_VERSION=%WindowsSDKVersion:~0,-1%

:: Directory which includes the sign.exe tool for Authenticode signing.
set OMAHA_SIGNTOOL_SDK_DIR=%WindowsSdkDir%\bin\x86

set PYTHONPATH=%OMAHA_PYTHON_DIR%

:: Directory of Scons (http://www.scons.org/).
set SCONS_DIR=%SCONS_DIR%

:: Directory of the Google's Software Construction Toolkit.
set SCT_DIR=%OMAHADEV%\third_party\swtoolkit



set PROXY_CLSID_TARGET=%~dp0proxy_clsids.txt
set CUSTOMIZATION_UT_TARGET=%~dp0common\omaha_customization_proxy_clsid.h

rem Force Hammer to use Python 2.4.  (The default of Python 2.6 exposes some
rem bugs in Scons 1.2, which we currently use.)
set PYTHON_TO_USE=python_24
call "%SCT_DIR%\hammer.bat" %*

if /i {%1} == {-c} (
  del /q /f "%PROXY_CLSID_TARGET%" 2> NUL
  del /q /f "%CUSTOMIZATION_UT_TARGET%" 2> NUL
)

REM If Omaha fails somewhere, it likes blaming ApplyTag

:error_no_vc
:end
:END
:: pause
```

**Comment by Jrock0138** [comment]
How do I apply this
