### ISSUE TITLE
Installation failed, Error code 0x80070002 

### ISSUE THREAD

**Issue by shiladkumard** [google/omaha#134]
Hi Good evening,

I am trying to get the Omaha working, I have configured the variables as per the documentation (omaha\doc\CustomizingOmaha.md) and able to run a build successfully, I have created .exe file from the command, 
>ApplyTag.exe EpicUpdateSetup.exe EpicSetup.exe "appguid={A3AA2AD6-C357-4BB3-9625-6550647D956D}&appname=Epic&needsadmin=False&lang=en". 

But I am facing two errors, 
1. Installation failed, Error code 0x80070002
When I clicked on the Help button, I got this URL, wherein it contains, error code, extra_code and all. 
https://www.updates.epicbrowser.com/support/installer/?hl=en&product=%7BA3AA2AD6-C357-4BB3-9625-6550647D956D%7D&error=0x80070002&extra_code=257&guver=1.3.99.0&m=0&os=10.0.16299.309&sp=&iid=&brand=&source=gethelp&testsource=auto

2. I am unable to sign the .exe file. 

![build successfull](https://user-images.githubusercontent.com/16273796/38572480-d77642ce-3d10-11e8-8e8a-3c5cc8420d59.png)
![installation error](https://user-images.githubusercontent.com/16273796/38572071-b062708c-3d0f-11e8-8a33-82d5386ee8dd.png)
![signtool - access is denied](https://user-images.githubusercontent.com/16273796/38572078-b4925d34-3d0f-11e8-9763-6563abc550e1.png)

I am struggling with these issues.  Please help me out for to fix them.

**Comment by sorinj** [comment]
You could inspect the debug log that the program creates when run in the debug mode. Or run the program under the debugger to identify what is causing the error.

**Comment by tkntjsdw** [comment]
![](https://user-images.githubusercontent.com/16273796/38572078-b4925d34-3d0f-11e8-9763-6563abc550e1.png)

**Comment by Raidersvalle13** [comment]
Help with chrome installation
