### ISSUE TITLE
Constant shell does not verify the signature of goopdate.dll

### ISSUE THREAD

**Issue by hologramas** [google/omaha#142]
Hi, more of a question than an issue.
The MD documentation of the constant shell mentions that the constant shell **might** verify the singnature of the goopdate.dll before loading it.  
The code does not seem to do this. Is this intentionally not done and the documentation is not up-to-date? or is it supposed to be done but was stripped out of Omaha for open-source purposes?

**Comment by Wayne24jr** [comment]
d41d8cd98f00b204e9800998ecf8427e

**Comment by sorinj** [comment]
At this time, the change in behavior is intentional. Omaha relies solely on the OS mechanisms to avoid side loading of DLLs.
