### ISSUE TITLE
NTDDI_VERSION not set correctly

### ISSUE THREAD

**Issue by macqm** [google/omaha#144]
The `NTDDI_VERSION` is set in the main.scons file with a `D` prefix: 
`'DNTDDI_VERSION=NTDDI_WINXPSP3'`.

Because it's in `CPPDEFINES` section, the prefix should be dropped. It would be valid in CPPFLAGS.

**Comment by sorinj** [comment]
Thank you, you could send a patch or we will upstream such a change soon. We are still working on fixing something related to this. We'd run into an issue specifically on XP platform, where recent protocol buffers dependencies added to the project broke the XPSP2 build because the protocol buffers code requires a few things from the C++11 concurrency library.

**Comment by macqm** [comment]
I think I messed up my PR a little.
I got:
```
C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared\sdkddkver.h(282): fatal error C1189: #error:  NTDDI_VERSION setting conflicts with _WIN32_WINNT setting
```
I tested with WIN7 values before changing back to XP SP2. I realized that I picked a value for XP SP3 for NTDDI_VERSION and now the sdkddkver.h complains about the mismatch.

I will fix that, however, the latest MSVC has an issue with the winioctl.h after setting NTDDI_VERSION:
```
omaha/precompile/precompile.h(77): error C2220: warning treated as error - no 'object' file generated
omaha/precompile/precompile.h(77): warning C5031: #pragma warning(pop): likely mismatch, popping warning state pushed in different file
C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um\winioctl.h(161): note: #pragma warning(push)
precompile/precompile.h(22): warning C5032: detected #pragma warning(push) with no corresponding #pragma warning(pop)
scons: *** [scons-out\dbg-win\obj\base\base_pch.pch] Error 2
scons: building terminated because of errors.
```
Which makes me think that hammer\scons doesn't set MSVC_VER correctly somehow or there is a real issue (like [this one](https://developercommunity.visualstudio.com/content/problem/230958/warning-c5032-detected-pragma-warningpush-with-no.html))in MSVC (I am using 15.9.8).

**Comment by macqm** [comment]
Created #146 to fix this issue. Sorry again for not double checking if it all builds fine after the first change.
