### ISSUE TITLE
Zlib can't load 'unistd.h' and other build errors

### ISSUE THREAD

**Issue by blingenau** [google/omaha#151]
Getting some errors on building the master branch
```
scons: warning: No installed VCs
File "C:\swtoolkit\site_scons\site_init.py", line 426, in SiteInitMain

scons: warning: No version of Visual Studio compiler found - C/C++ compilers most likely not set correctly
File "C:\swtoolkit\site_scons\site_init.py", line 426, in SiteInitMain
scons: Reading SConscript files ...

scons: warning: No installed VCs
File "C:\swtoolkit\site_scons\site_tools\target_platform_windows.py", line 283, in generate

scons: warning: No version of Visual Studio compiler found - C/C++ compilers most likely not set correctly
File "C:\swtoolkit\site_scons\site_tools\target_platform_windows.py", line 283, in generate
Using precompiled headers.
Building versions: 1.3.99.0
python C:\omaha-client\omaha\tools\proxy_clsid_utils.py
scons: done reading SConscript files.
scons: Building targets ...
scons: building associated VariantDir targets: scons-out
________Compiling scons-out\dbg-win\obj\base\libzip\zip_add_dir.obj
zip_add_dir.c
c:\omaha-client\third_party\zlib\v1_2_11\zconf.h(475): fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory
scons: *** [scons-out\dbg-win\obj\base\libzip\zip_add_dir.obj] Error 2
scons: building terminated because of errors.
```

This was run from an elevated Developer Command Prompt for VS 2017.

**Comment by sorinj** [comment]
It is possible that the VC build environment is not set up for the command line window where the build is running. Have you run vcvars32.bat script from Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Auxiliary\Build ?

**Comment by sorinj** [comment]
For some reason, it seems that building zlib\v1_2_11\zconf.h(475) is trying to include 'unistd.h', which is a UNIX library file. Maybe for some reason, the 'zconf.h' thinks it has HAVE_UNISTD_H, which comes from the omaha\base\libzip\config.h. You'd have to look and see what symbols are defined in config.h. Then, you could undefined HAVE_UNISTD_H if that is the case.

Alternatively, you could try patching the zlib\v1_2_11\zconf.h with something like:

if defined(_WIN32)
#      include <io.h>
#    else
#      include <unistd.h>         /* for SEEK_*, off_t, and _LFS64_LARGEFILE */
#    endif
