### ISSUE TITLE
'search': is not a member of 'std'

### ISSUE THREAD

**Issue by blingenau** [google/omaha#152]
Running `hammer --no-use_precompiled_headers --all` yields this error:
```
base\apply_tag.cc(206): error C2039: 'search': is not a member of 'std'
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\map(20): note: see declaration of 'std'
base\apply_tag.cc(206): error C3861: 'search': identifier not found
scons: *** [scons-out\dbg-win\obj\base\apply_tag.obj] Error 2
scons: building terminated because of errors.
```

**Comment by sorinj** [comment]
Does it work if you:
#include <algorithm>
in the file base\apply_tag.cc ?

**Comment by macqm** [comment]
Adding `#include <functional>` fixes apply_tag.cc, but more and more errors keep popping up. To me it looks like building **without** precompiled headers it's completely broken. All the ATL headers require disabling some specific warnings and precompile.h takes care of it.

**Comment by davissheryl1** [comment]
@blake Lingenau the reason I got knocked out from GitHub 3 to 5 days ago was someone was haking my account and I was trying to get my studio up and working.  every time I tried to clean it up @ reimage a place where I bought my driver app was tracking me and the more I delete, they track behind me every day.

**Comment by sorinj** [comment]
Using precompiled headers was a mistake imo, but at the time when the project was started, build times was a major issue. I may send a PR to disable using precompiled headers though.

**Comment by sorinj** [comment]
Using precompiled headers has been removed on origin/master.

**Comment by davissheryl1** [comment]
what do you mean my header has been removed on origin/master.  I been having bad experiences with you all and I am tired, no support or nobody to talk to, but you want to remove my headers, something I was not instructed on doing!  I been patient for too long and I don't want to continue with this anymore.
