### ISSUE TITLE
Buidl break on configurations following the readme. zipconf.h cannot be found.

### ISSUE THREAD

**Issue by hologramas** [google/omaha#154]
It seems we are missing some instructions on the MD.
I was able to workaround the break by adding the following:
 '$THIRD_PARTY/libzip/xcode' to CPPPATH in /omaha/base/build.scons on the "Add libzip library files" section.

I don't know if other people will run into that.
I will send a PR in case you want to take it.

**Comment by hologramas** [comment]
Issue has to do with ziplib and the readme being incomplete.

**Comment by sorinj** [comment]
I uploaded a patch to make it build with the lastest libzip 1.5.2. Could you please give it a try? Thank you!

**Comment by hologramas** [comment]
Will do

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
