### ISSUE TITLE
How does one perform a self update of the client?

### ISSUE THREAD

**Issue by blingenau** [google/omaha#183]
I have my server set up so that it responds to update checks of the omaha client GUID and returns the new `GoogleUpdateSetup.exe` with the `/update` argument. The problem is that it doesn't update the `GoogleUpdate.exe` that's sitting in `C:\Program Files`. But it does put the new version in my `%LocalAppData%`. Is this the expected behavior? Should it be updating the systemwide version?

**Comment by macqm** [comment]
I think you need to run as the SYSTEM user.
If you look at the `bool IsMachineProcess` method, you will see:
```
    // The following all run silently as the user for user installs or Local
    // System for machine installs.
    case COMMANDLINE_MODE_UPDATE:
    case ...:
      return is_local_system;
```
Since you are not running as the SYSTEM, then `IsMachineProcess` returns false and the update continues in `%LOCALAPPDATA% instead.

One way to test self-updates is to use [psexec](https://docs.microsoft.com/en-us/sysinternals/downloads/psexec) from the Sysinternals.

**Comment by blingenau** [comment]
But the update is run from the running GoogleUpdate service, right? Isn't that update service running as the SYSTEM user?

**Comment by macqm** [comment]
That is my understanding too. The /svc process should run as "Local System". And so should be the scheduled task (/ua).

I'd try to confirm that `/update` process is being run as SYSTEM with the Process Monitor.

From my limited understanding of Omaha I think there is no other way.
When you run `/update` mode it goes from
`GoopdateImpl::DoSelfUpdate()`
to
`install_self::UpdateSelf(is_machine_, args_.session_id);`
note: here the `is_machine_` should be set by `IsMachineProcess`.

From there it calls `internal::DoSelfUpdate` and
`DoInstallSelf(is_machine, true, false, false, extra_code1)`,
which creates and instance of `Setup`:
`Setup setup(is_machine);`
and calls:
`Setup::Install` (it should log if it's an elevated user here).
and then finally the actual install updates from `SetupFiles::Install`. 
Here it will decide where to put files based on the `is_machine`:
```
  // Copy the core program files.
  CPath install_dir = goopdate_utils::BuildInstallDirectory(is_machine_,
                                                            GetVersionString());
```

So for some reason `is_machine` is `false` in your case, i.e. `/update` was not run by the SYSTEM user.
Perhaps the service is run as SYSTEM but for some reason it impersonates the logged in user when spawing the `/update` process?

**Comment by blingenau** [comment]
Does the server need to somehow respond that this self update has `needsadmin=True`?

**Comment by Kimcarlobriones** [comment]
Update

**Comment by Kimcarlobriones** [comment]
Not work

**Comment by macqm** [comment]
@blingenau I am not aware of that.
Were you able to confirm that the self-update runs as SYSTEM user?
