### ISSUE TITLE
Syntax error trying to compile

### ISSUE THREAD

**Issue by mherrmann** [google/omaha#193]
I'm trying to build the latest HEAD version `1b18ab3`. I have Visual Studio 2019 Community Update 16.3.6 (I couldn't find 16.3.0 as suggested by the Developer Setup Guide). When I try to compile with `hammer`, I get:

```
________Compiling scons-out\dbg-win\obj\common\update3_utils.obj
update3_utils.cc
...\third_party\wtl\include\atlgdi.h(1759): error C2760: syntax error: unexpected token ')', expected 'expression'
...\third_party\wtl\include\atlgdi.h(3353): note: see reference to class template instantiation 'WTL::CDCT<t_bManaged>' being compiled
...\third_party\wtl\include\atlgdi.h(1781): error C2760: syntax error: unexpected token ')', expected 'expression'
...\third_party\wtl\include\atlgdi.h(2383): error C2760: syntax error: unexpected token 'identifier', expected ';'
...\third_party\wtl\include\atlgdi.h(2876): error C2760: syntax error: unexpected token ')', expected 'expression'
scons: *** [scons-out\dbg-win\obj\common\update3_utils.obj] Error 2
scons: building terminated because of errors.
```

Do you happen to have an idea what might be causing this?

**Comment by sorinj** [comment]
Could you please post the entire command line of the compiler? Run: hammer --verbose to get it.

**Comment by mherrmann** [comment]
Of course, thank you for the prompt reply. I have uploaded the output of `hammer --verbose`: [link](https://www.dropbox.com/s/o0ndz346yvfpgi3/output.txt?dl=1)

Actually, now that we are in touch: I already have an older revision of Omaha set up to compile correctly. My motivation for updating to the latest one is that I hope it will use TLS 1.2 instead of TLS 1.0. Do you happen to know if the current version of Omaha does this?

**Comment by sorinj** [comment]
Omaha is using the OS default configuration to select which version of the protocol to use. The Omaha code is not setting any value for WINHTTP_OPTION_SECURE_PROTOCOLS.

**Comment by mherrmann** [comment]
Thank you. So if the OS default is TLS 1.0 (which as far as I know is the case in Windows 7), then even the current HEAD version of Omaha will use it. Is that correct?

**Comment by sorinj** [comment]
This is what I expect to happen. We are taking a look at the TLS issue, thank you for bring it up.

**Comment by mherrmann** [comment]
What we see is that at least on Win 7, Omaha uses TLS 1.0. However, if [Windows Update 3140245](https://support.microsoft.com/en-us/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-default-secure-protocols-in-wi) is installed and the `DefaultSecureProtocols` registry value is set to `0x00000800`, then TLS 1.2 is used.

**Comment by sorinj** [comment]
It looks like Omaha has the expected behavior in this case. As said, Omaha is not setting up any WINHTTP_OPTION_SECURE_PROTOCOLS, and will use whatever the OS stack chooses for it.
Is my understanding correct?

**Comment by mherrmann** [comment]
I think so, yes.

**Comment by mherrmann** [comment]
Another question: What would be the best way to change this? Is it safe to just set `WINHTTP_OPTION_SECURE_PROTOCOLS` in `SimpleRequest::Connect` for instance?

**Comment by mherrmann** [comment]
Sure, sorry.

**Comment by sorinj** [comment]
I am not able to repro the compile time error with 16.3.6 and WTL version 10.0.9163 (2019-06-12).
Could you please update to the WTL so we can refer to the same lines of code?
Also what is the output of running `cl` in your build command window? 
After cleaning up the PII and other irrelevant information, could you please post here the output of running `set` in your build window. 
I am building with `VSCMD_VER=16.3.6, WindowsSDKVersion=10.0.18362.0,VCToolsVersion=14.23.28105Platform=x86
PreferredToolArchitecture=x64`
