### ISSUE TITLE
End of Life (EOL) for Python 2.7, Omaha build depend on.

### ISSUE THREAD

**Issue by sudoudaisuke** [google/omaha#206]
Building Omaha depend on Python 2.7 and SCons 1.3. But Pyhone 2.7 will be EOL on 2020/01/01.
Are there any plan switching Omaha Build?

**Comment by SRYPPR00** [comment]
> อาคารโอมาฮาขึ้นอยู่กับ Python 2.7 และ SCons 1.3 แต่ Pyhone 2.7 จะเป็น EOL ในวันที่ 2020/01/01
> มีแผนจะเปลี่ยน Omaha Build หรือไม่?

**Comment by sorinj** [comment]
Speaking from the Google side, we don't have any plans to make changes to the build system at the moment. We are ramping up our effort on https://cs.chromium.org/chromium/src/chrome/updater/ so significant changes to the existing code base are going to be challenging.

I expect the bulk of the work of making Omaha build with Python 3.x to go into fixing "Software Construction Toolkit (Hammer)", which sadly, it is an unmaintained project.

Some of us have tried porting the current build scripts to GN.

**Comment by sudoudaisuke** [comment]
Thank you for your comment.
I close this issue.
