### ISSUE TITLE
Hammer ends with "The system cannot find the path specified."

### ISSUE THREAD

**Issue by mano7onam** [google/omaha#210]
I have installed all necessary libraries from the list and started to build omaha. I run visual studio bat script and then run hammer and took "The system cannot find the path specified."

![image](https://user-images.githubusercontent.com/20560572/75085448-f9d39780-555b-11ea-81a1-1625fed16b66.png)

Should I add something else in path or maybe the problem is something in path can not be found by system?

Also I tried to run bat scripts for x86, amd64_86 but with the same error.

**Comment by sorinj** [comment]
It is possible that hammer.bat complains that it can't run ```call "%SCT_DIR%\hammer.bat" %*```. I suggest using some echo statements in the scripts to figure it out.

**Comment by mano7onam** [comment]
Can I use prints in .scons files to see variables values?
I don't know how but now it run hammer and it started to do something. But something is completely wrong :(
Now I have this error:
![image](https://user-images.githubusercontent.com/20560572/75601498-4a17a000-5aee-11ea-8a2c-1b4d33402758.png)
And I want to somehow log variables from scons. 

Also it seems like I doing something completely wrong (maybe don't set some environment variables or don't install some package). What can be the reason of such problems?

**Comment by mano7onam** [comment]
Created new issue. I’ll close this one because I’ve moved a little further :)
