### ISSUE TITLE
SConsEnvironmentError: No module named _scons_optparse

### ISSUE THREAD

**Issue by mano7onam** [google/omaha#214]
I have some problem with scons. What can be the reason of such problem? Can I maybe forget to set some environment variable or add something to path variable?

What I did? I changed scons to real scons path (in hammer.bat):
![image](https://user-images.githubusercontent.com/20560572/75601670-fad26f00-5aef-11ea-84fb-685c76d8d3a3.png)
It's there:
![image](https://user-images.githubusercontent.com/20560572/75601758-ee024b00-5af0-11ea-8757-607d37bfbb25.png)

Changed path to "Go" (possible it's not necessary)
![image](https://user-images.githubusercontent.com/20560572/75601680-13db2000-5af0-11ea-9c29-c223b5c6a3d6.png)

But I have some problem there:
![image](https://user-images.githubusercontent.com/20560572/75601711-687e9b00-5af0-11ea-88e6-05fdeb019d83.png)

This is an error message:
`scons: Reading SConscript files ...
SConsEnvironmentError: No module named _scons_optparse:
  File "H:\omaha\omaha\main.scons", line 151:
    SIGNTOOL = _signtool_path,
  File "C:\Python27\Lib\site-packages\scons\SCons\Environment.py", line 990:
    apply_tools(self, tools, toolpath)
  File "C:\Python27\Lib\site-packages\scons\SCons\Environment.py", line 102:
    env.Tool(tool)
  File "C:\Python27\Lib\site-packages\scons\SCons\Environment.py", line 1809:
    tool = SCons.Tool.Tool(tool, toolpath, **kw)
  File "C:\Python27\Lib\site-packages\scons\SCons\Tool\__init__.py", line 122:
    module = self._tool_module()
  File "C:\swtoolkit\site_scons\site_init.py", line 307:
    module = self._tool_module_orig()
  File "C:\Python27\Lib\site-packages\scons\SCons\Tool\__init__.py", line 159:
    raise SCons.Errors.SConsEnvironmentError(e)`

![image](https://user-images.githubusercontent.com/20560572/75601726-8ea43b00-5af0-11ea-9264-80e0a54f76b5.png)

What can be the reason of it?

**Comment by mano7onam** [comment]
And why _is_google_update_build is turned off by default? _is_google_update_build
![image](https://user-images.githubusercontent.com/20560572/75601808-9a443180-5af1-11ea-8d1e-7a7e30270222.png)

**Comment by sorinj** [comment]
_is_google_update_build turns on some of the Google-specific features in the build such as 
```if _is_google_update_build:
        # Google Update includes integration specific to Google Chrome, which
        # should not be present in other forks of Omaha.
        win_env.Append(
            CPPDEFINES = ['HAS_LEGACY_DM_CLIENT'],
        )
``` 
It's not a good way to customize the build and we had ideas to change 
we but never gotten to it:
``` 
# Build the "Google Update", the Google-specific version of Omaha.
# TODO(omaha): Set based on an environment variable and/or Hammer arg.
```
A different way to do it could have been to have more specific build args, such as ```has_device_management```.

**Comment by sorinj** [comment]
Regarding the build, I don't know why the build is failing but I wonder if you've correctly installed scons-1.3.1 as we suggested. For instance, my path looks like ```C:\Python27\Lib\site-packages\scons-1.3.1``` where in the screenshot you've posted it looks different. And I see a trace of scons-3.1.1, which seems concerning.

I know some people have made improvements to the build so that they could build with newer versions of Python and SCons. For now, I suggest trying the versions we know work, and iterate from there.
