### ISSUE TITLE
Clarification on Omaha.

### ISSUE THREAD

**Issue by Mohan-V-P** [google/omaha#221]
I need a clarification on Omaha. I'm seeing only the executable file for the updating the application. 
1. Is Omaha only used for the auto-updation?
2. How can we use this for first time installation? please help me on how to configure Omaha for the first time installation.
3. Also for auto-updation, should we have a another server called update server? Please do elaborate on this mechanism. (Do Omaha protocol v2 and v3 follow the same mechanism for auto-updation?)  
4. Is Omaha used to update all the google product installed on the PC?

Sorry if these questions are poor. I'm new to this. Please don't get irritated for my questions.

**Comment by sorinj** [comment]
1. Omaha is typical used for installing a new product, and then auto-updating it. But it could only be used for updates only.
2. Omaha has the concept of metainstallers. A metainstaller is essentially a generic Omaha setup plus a string, which is a `tag`. The tag tells Omaha what product it needs to download and install. An example of a tag is something like this: 
` c:\temp>ReadTag.exe Tagged_SampleSetup_en.exe
Tag = 'appguid={D6B08267-B440-4c85-9F79-E195E80D9937}&appname=Sample&needsadmin=True&lang=en'`
This tells Omaha to install the product `Sample`, which in the update server is identified by the following appid `{D6B08267-B440-4c85-9F79-E195E80D9937}`. You can see this by using the `readtag.exe` and the `Tagged_SampleSetup_en.exe` we build in the scons-out directory, I believe if -`-all` is used on hammer command line.
3. The same server is used in both install and update cases. Omaha v3 protocol should be used.
4. Omaha is used to update some of the Google products on the PC. Keep in mind that the open source version of Omaha is not the version that Google ships to its customers. Google builds its updater from similar source code but its not the version that builds from github.

**Comment by Mohan-V-P** [comment]
Thank you very much. It helped me to understand. I think this answer will also help the newbies like me.
