### ISSUE TITLE
Omaha and Python 2.x support / estimated EOL

### ISSUE THREAD

**Issue by mattafire** [google/omaha#250]
Extending the discussion from this issue https://github.com/google/omaha/issues/206 

After a year of Python 2.7 being EOL, what is the outlook of this Omaha project being sun setted (projected EOL of this project)?

And/or is there any outlook of this project being updated to be more industry standard instead of becoming legacy technology?

And/or is this project just in bug/vulnerability fix mode?

I do know that one of the responses pointed out what is coined Omaha 4 (Chromium updater). Is that the proposed direction to eventually move toward with little support for this project?

**Comment by sorinj** [comment]
There is no defined timeline for sunsetting this project. The team is actively working on https://source.chromium.org/chromium/chromium/src/+/master:chrome/updater/ but there is a lot of work that remains to be done until Google can replace its current Chrome updater with anything else. Therefore, there are no plans for terminating the Omaha project right now.

The Omaha project is closer to its end though. Right now, the team is focused more on making progress on //chrome/updater than improving Omaha, but work in Omaha still happens, as illustrated by the commit log.

Google addresses all the security vulnerabilities we are aware of but bug fixes are provided only as-needed, and especially for significant issues. We've not planned any work to address the Python 2.7 issue, or to change the build system. Are there other specific industry-standards you'd like to mention?

The intention for Google is to complete the Chromium updater and migrate its user base to that. That is how we hope we could bring the updater to industry standards and better quality overall.

We understand the Python 2.7 is an issue. My opinion is that it is the Software Construction Toolkit that needs to be brought
up to date. The code in Omaha could be ported easily to Python 3 (I recall I made a bunch of changes related to that) and SCONS works with Python 3 as well.

**Comment by mattafire** [comment]
@sorinj I appreciate the answer with such transparency.  That is what I was looking for.  I have no other questions currently.
