### ISSUE TITLE
Mac version?

### ISSUE THREAD

**Issue by jgwinner** [google/omaha#264]
Is there a Google based code version of Omaha for the Mac ecosystem?

**Comment by mherrmann** [comment]
Hi John, I don't think so. People typically use [Sparkle](https://sparkle-project.org/) instead.

**Comment by jpawlicki** [comment]
There is work being done in Chromium on this; see https://bit.ly/chromium-updater.

**Comment by mherrmann** [comment]
@jpawlicki do you know if there is an ETA?

**Comment by sorinj** [comment]
There is a cross-platform updater in development at https://source.chromium.org/chromium/chromium/src/+/master:chrome/updater/

**Comment by jgwinner** [comment]
Ah. I see there's a "Sparkle" and a "WinSparkle" so that could work. However, we were looking for something that would also track installs, etc. Sort of like LogMeIn does, but Mac and PC.

**Comment by mherrmann** [comment]
@jgwinner my company https://omaha-consulting offers a server implementation for Sparkle and Omaha that shows usage statistics. Eg.:

![image](https://user-images.githubusercontent.com/1076393/111664308-f0c20200-8811-11eb-91d6-40c648aca7b1.png)

**Comment by jgwinner** [comment]
Interesting! I'll certainly add it to my matrix. Thanks.

We're just a small startup, mostly working remote at this point. Maybe fifty users max.

        == John ==

**Comment by jpawlicki** [comment]
Regarding ETA for https://bit.ly/chromium-updater, it depends on what is needed.

Google has some backward compatibility and feature parity constraints that still need work. We're hoping to start using it around the end of the year on both Windows and Mac.
Other collaborators are starting to use it now on Mac.

**Comment by mherrmann** [comment]
Thanks!

**Comment by rpaul577** [comment]
I don't these people I have got laptop stolen from me so thing should is iPhone 11 if see any body on phone others company shut them down please fix ASAP
