### ISSUE TITLE
Code Red

### ISSUE THREAD

**Issue by mmxw11** [google/omaha#293]
Hey,

I've been trying to understand how "Code Red" actually works. Code Red is defined as following.

> “[Code Red](https://github.com/google/omaha/blob/master/doc/Omaha3Walkthrough.md)” - Describes a situation where a bugged Omaha build or an OS patch has been released that prevents Omaha from updating for a very large percentage of users, and the tools for resolving it. Google-authored applications can link with a static library produced during the Omaha build that checks for Code Red releases through an alternate channel; if a Code Red release is enabled, an executable is downloaded which attempts to repair/reinstall Omaha.

This implies that Code Red is meant only for Google-authored applications. However, after digging into the source code and documentation. I noticed when the Core runs, it will do a code red check as described [here](https://github.com/google/omaha/blob/master/doc/GoogleUpdateOnAScheduleOverview.html#L596) and [source here](https://github.com/google/omaha/blob/master/omaha/goopdate/goopdate.cc#L1108). Effectively this means the Core task will also periodically check for Code Red releases.

It's quite unclear to me how this is supported to work. These calls ultimately end up in [google_update_recovery#FixGoogleUpdate](https://github.com/google/omaha/blob/master/omaha/recovery/client/google_update_recovery.cc#L607). Declaration for this function in the header file [google_update_recovery.h](https://github.com/google/omaha/blob/master/omaha/recovery/client/google_update_recovery.h#L40) has the following documentation.

> Determines whether there is a Code Red event for the current installation and repairs it if necessary. app_language should follow the external Internet standard Best Common Practice (BCP) 47: http://www.rfc-editor.org/rfc/bcp/bcp47.txt context can be NULL if download_callback does not use it.

However, I can't find anything in the function definition that determines "Code Red Event". The function just tries to download whatever there's available and immediately try to repair itself.  That effectively means the client just tries to repair itself every day for no reason when the Core runs. That doesn't really make any sense to me? I tried this with the official Omaha Client and Google Server. Every single time it will return HTTP 204 status for this request, effectively negating it's purpose. Regardless of what query parameters I give it, I always end up with that response. The following http request is directly from the official Google Omaha client logs.

> https://clients2.google.com/service/check2?crx3=true&appid=%7B430FD4D0-B729-4F61-AA34-91526481799D%7D&appversion=1.3.36.82&applang=&machine=1&version=1.3.36.82&userid=&osversion=10.0&servicepack=

 Am I missing something but I can't figure out how is it determined if something is actually broken? How is this supposed to work if the Google Server is never returning any payloads.

**Comment by sorinj** [comment]
If the CodeRed server returns 200 OK and a valid payload, Omaha is going to validate the  payload, and run it. Google decides under which conditions such a payload is returned.

**Comment by mmxw11** [comment]
Thanks for the clarification.

I see, so all the logic to determine whether there is a "Code Red Event" is on the server. This is going more towards the server implementation than client, but just out of curiosity. I understand if you _can't_ answer this, but based on the data the client sends, I think it's ambiguous to determine whether it's broken. That got me thinking, maybe Code Red is just a manual switch that can be turned on the server when everything else fails.

**Comment by sorinj** [comment]
That is correct, yes. CodeRed is a last-resort mechanism, intended to be applied at a large scale.

**Comment by mmxw11** [comment]
That explains it all. I'll go ahead and close this issue/question.
