### ISSUE TITLE
Build Issue 

### ISSUE THREAD

**Issue by MadnessAN** [google/omaha#299]
Hello, 
I have a build issue :

scons: done reading SConscript files.
scons: Building targets ...
scons: building associated VariantDir targets: scons-out
________Compiling scons-out\dbg-win\obj\goopdate\job_observer.obj
job_observer.cc
goopdate\job_observer.cc(144): error C2064: term does not evaluate to a function taking 0 arguments
goopdate\job_observer.cc(163): error C2064: term does not evaluate to a function taking 0 arguments
goopdate\job_observer.cc(173): error C2064: term does not evaluate to a function taking 0 arguments
goopdate\job_observer.cc(182): error C2064: term does not evaluate to a function taking 0 arguments
goopdate\job_observer.cc(194): error C2064: term does not evaluate to a function taking 0 arguments
goopdate\job_observer.cc(203): error C2064: term does not evaluate to a function taking 0 arguments
goopdate\job_observer.cc(213): error C2064: term does not evaluate to a function taking 0 arguments
scons: *** [scons-out\dbg-win\obj\goopdate\job_observer.obj] Error 2
scons: building terminated because of errors.

anyone have a idea ?

**Comment by mherrmann** [comment]
See #295.

**Comment by MadnessAN** [comment]
@mherrmann thank you.
I had to change the GO versions for 1.15 x64
and Google Protocol Buffers 3.13.0 not higher.
but now I have this :

python F:\Repos\omaha\omaha\tools\proxy_clsid_utils.py
scons: done reading SConscript files.
scons: Building targets ...
scons: building associated VariantDir targets: scons-out
"C:\go/bin/go.exe" run F:\Repos\omaha\omaha/../common/certificate_tag/certificate_tag.go -set-superfluous-cert-tag=Gact2.0Omaha -padded-length=8206 -out scons-out\dbg-win\obj\installers\GoogleUpdateSetup.exe scons-o
ut\dbg-win\obj\installers\authenticode_GoogleUpdateSetup.exe
Exception 0xc0000005 0x0 0x7fff43850fff 0x278fb830000
PC=0x278fb830000

runtime: unknown pc 0x278fb830000
stack: frame={sp:0xb88f9fe1a0, fp:0x0} stack=[0x0,0xb88f9ff880)
000000b88f9fe0a0:  000000b88f9fe0e8  000000b88f9fe110
000000b88f9fe0b0:  000000b88f9fe0d8  000000b88f9fe0d0
000000b88f9fe0c0:  000000b88f9fe0d4  00000278d6351140
000000b88f9fe0d0:  0000000000000000  0000000000000000
000000b88f9fe0e0:  0000000000000000  0000000000000005
000000b88f9fe0f0:  000000b88f9fe238  00007fff411db6cf
000000b88f9fe100:  00000278d64229c0  00007fff4368345e
000000b88f9fe110:  00007fff436500e8  00000278d6453e50
000000b88f9fe120:  00007fff411db6c9  000000b88f9fe170
000000b88f9fe130:  004f0044004e0049  0053005c00530057
000000b88f9fe140:  00000278d64229c0  0000000000000000
000000b88f9fe150:  00000278d6452e80  006c006400050005
000000b88f9fe160:  00007fff411db6c9  0000000000000000
000000b88f9fe170:  00007fff00000000  00007fff436500e8
000000b88f9fe180:  0000000000000000  0000000000000000

...

**Comment by sorinj** [comment]
I am using go1.14.2 for my builds. It looks like the tagging script crashes. Could you please try downgrading golang and see if the problem isolates to the golang version, or it is something else. It could be a bug in the script (maybe it does not handle an error) or a problem with the signed GoogleUpdateSetup.
