### ISSUE TITLE
Rollback MSEdge

### ISSUE THREAD

**Issue by elinside** [google/omaha#337]
Hi there.
I am not sure if I'm in the right place here, but I try to place my question :)

We are using the Microsoft Edge Rollback Keys in the registry for managing companywide rollbacks.
Today I'd like to rollback to an earlier Version, (ex. 95.0.1020.30, doesn't matter). 
So I set these 2 keys, which worked perfectly at the beginning of september... 

powershell example:

```
    $TargetVersion = "95.0.1020.30"
    Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\EdgeUpdate" -Name "RollbackToTargetVersion{56EB18F8-B008-4CBD-B6D2-8C97FE7E9062}" -Value "1"
    Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\EdgeUpdate" -Name "TargetVersionPrefix{56EB18F8-B008-4CBD-B6D2-8C97FE7E9062}" -Value $TargetVersion 
```

Now, the first one don't work, so I cannot rollback. In the logfile I keep seeing the following error:
[11/08/21 16:05:41.848][MicrosoftEdgeUpdate:msedgeupdate][8028:816][ConfigManager::LoadGroupPolicies][Unexpected String policy prefix encountered][RollbackToTargetVersion{56EB18F8-B008-4CBD-B6D2-8C97FE7E9062}][1]

**Comment by mistychatmsn** [comment]
So if you don't mind me asking how can I find out where are all my assets
at and how do I find out more information about it

**Comment by GitHubGanesh** [comment]
RollbackToTargetVersion is expected to be a DWORD value of either 0 or 1. We were not enforcing this before, but now we are in the latest version. So if you write it as a DWORD instead of a String as you are doing, things should work.

**Comment by elinside** [comment]
Thanks. It's working again :)
