### ISSUE TITLE
CupEcdsaRequestTest.PostSimpleRequestHttps is broken.

### ISSUE THREAD

**Issue by sorinj** [google/omaha#359]
Note: Google Test filter = CupEcdsaRequestTest.PostSimpleRequestHttps
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from CupEcdsaRequestTest
[ RUN      ] CupEcdsaRequestTest.PostSimpleRequestHttps
net\cup_ecdsa_request_unittest.cc(91): error: Expected: (http_request->Send()) succeeds.
  Actual: 0x80072EE7

net\cup_ecdsa_request_unittest.cc(97): error: Value of: http_status == HTTP_STATUS_OK || http_status == HTTP_STATUS_PARTIAL_CONTENT
  Actual: false
Expected: true
[  FAILED  ] CupEcdsaRequestTest.PostSimpleRequestHttps (19 ms)
[----------] 1 test from CupEcdsaRequestTest (20 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (43 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] CupEcdsaRequestTest.PostSimpleRequestHttps

**Comment by sorinj** [comment]
It looks like this change broke the test: https://github.com/google/omaha/commit/18a24cf032136047f21dfeaead6ce77fad8bb6f9#diff-db419d84d3b27b50595d6b3ee125ce09b8ca01fa63fdcd168939efada9808f00R43

**Comment by sparist** [comment]
Oops. Should be fixed here: https://github.com/google/omaha/pull/361
