### ISSUE TITLE
The king  iPhone12 pro max

### ISSUE THREAD

**Issue by Theking88np4** [google/omaha#373]

**Comment by Theking88np4** [comment]
________________________________
From: The king ***@***.***>
Sent: Wednesday, February 16, 2022 4:13 PM
To: google/omaha ***@***.***>
Cc: The king ***@***.***>; Your activity ***@***.***>
Subject: [google/omaha] The king iPhone12 pro max (Issue #373)

**Comment by Sososweet69** [comment]
https://github.com/google/omaha/issues/373#issuecomment-1041344814
