### ISSUE TITLE
setup_files_unittest.cc fix for rebranded product 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/omaha#43]
```
When anybody does a rebranding of omaha, the unit test InstallHelper 
in file setup_files_unittest.cc might fail, because the test expects 
specific order of files returned by FindFiles(version_path, _T("*.*"), &files) 
invocation.

This patch fixes the issue.

See also:

  https://groups.google.com/group/omaha-dev/browse_thread/thread/d266ed52f2871069

```

Original issue reported on code.google.com by `kobalicek.petr` on 10 Sep 2012 at 5:36

Attachments:
* [omaha_setup_files_unittest.patch](https://storage.googleapis.com/google-code-attachments/omaha/issue-43/comment-0/omaha_setup_files_unittest.patch)

**Comment by sorinj** [comment]
I am not certain the patch is needed anymore, but if it is, we can reopen the bug.
