### ISSUE TITLE
Standalone installer without standalone_installers.txt

### ISSUE THREAD

**Issue by mherrmann** [google/omaha#432]
Hello,

as far as I'm aware, the `standalone_installers.txt` mechanism requires invoking Omaha's build for every new version and every application I want to generate an offline installer for. This requires setting up Omaha's build, which is rather heavyweight. I'm hoping there is an easier way of generating standalone installers.

One thing that would make it exceptionally easy is if one of Omaha's binaries offered a command line way to silently (and without connecting to the internet) install Omaha itself. Then that binary could just be invoked as part of an application's main installer.

Is this possible somehow?

Thank you,
Michael

**Comment by GitHubGanesh** [comment]
Once you have `mi_exe_stub.exe` built, then invoking `standalone_installer.BuildOfflineInstallersVersion` for each version/application should be quick and lightweight. You would not need to build Omaha itself each time.

Omaha offers a way to install silently without any applications, it's called `runtime` mode:
        GoogleUpdateSetup /install "runtime=true&needsadmin=false" /silent

Set needsadmin appropriately.  You can specify the usual set of Omaha tag parameters -- brand, browser, usagestats, etc. -- for Omaha if you wish.  

Omaha will install itself to the usual location (Program Files for needsadmin=true, the user's AppLocal directory for needsadmin=false), install scheduled tasks and COM APIs as normal, and record its current time in the Registry.  If there are no registered products within 24 hours of the runtime install, it will uninstall at the next automatic update check.

**Comment by mherrmann** [comment]
That is very helpful. Thank you @GitHubGanesh.
