### ISSUE TITLE
Is goopdateres_ui.rc missing?

### ISSUE THREAD

**Issue by mikehearn** [google/omaha#454]
I was browsing the code to try and find where exactly dialog resources are being defined in the code (e.g. for the layout of the progress window), but the trail seems to end with a file called goopdateres_ui.rc that isn't in the source tree. Is this a generated file, or if so, where does the IDD_PROGRESS resource actually get defined?

**Comment by GitHubGanesh** [comment]
goopdateres_ui.rc is used internally with grit to generate the dialog in various languages. 

For english, the resource is https://chromium.googlesource.com/external/omaha/+/17023a97fb2632e4d4f109616a7efa2cb946bb72/goopdate/resources/goopdateres/generated_resources_en.rc, which has IDD_PROGRESS.

**Comment by mikehearn** [comment]
Thank you!
