### ISSUE TITLE
Broken sure won't let me log in 

### ISSUE THREAD

**Issue by Omegamillinz** [google/omaha#464]
https://github.com/web-platform-tests/wpt/blob/master/html/links/icon/no-load-event.html

**Comment by CMOT09** [comment]
ผมไม่เข้าใจความหมายของคุณและไม่ได้มีเจตนาที่จะปิดกั้นอะไรคุณ
แต่ถ้าทุกสิ่งที่เกิดขึ้นมันทำให้ผมรู้สึกไม่ปลอดภัยหรือถูกเอาเปรียบผมก็จะไม่ยอมให้มันเกิดขึ้น
