### ISSUE TITLE
Calling 32 bit COM server from x64/arm64 client

### ISSUE THREAD

**Issue by mherrmann** [google/omaha#521]
Omaha registers 32 and 64 bit COM proxies in [google_update.cc](https://github.com/google/omaha/blob/483954725843b96b2adb3eb91bc2b233733224fb/omaha/goopdate/google_update.cc#L249). This lets both 32 and 64 bit processes call the on-demand update API.

I want to perform on-demand update checks from a native arm64 application in addition to an x64 app. The problem is that, at least in my tests, arm64 processes read the COM information from the same place in registry as x64 processes. If I register an x64 proxy, then the arm64 application is not able to instantiate the COM API. If I register an arm64 proxy, then the same happens to the x64 app.

My best idea for a solution is to try to make the arm64 app instantiate the 32 bit COM API via `CLSCTX_ACTIVATE_32_BIT_SERVER`. Is this sensible? If yes, why is the 64 bit proxy needed at all? Couldn't then also 64 bit clients invoke the 32 bit COM server in the same way?

**Comment by mherrmann** [comment]
An alternative solution could be to redirect the registry on arm64 before registering and reading the COM proxies.

**Comment by sorinj** [comment]
I apologize for the late answer, not sure it is relevant anymore. 
Omaha is using custom proxies for COM IPC. These are built as x86 and x86-64 DLLs which can't be loaded by native ARM64 processes. I don't know if any workaround exits. For now, our team has concluded that ARM64 clients can't communicate with Omaha as it is right now.

**Comment by mherrmann** [comment]
Thank you. We came to the same conclusion; The only possible solution we could think of would be via Arm64EC. See for example https://github.com/brave/brave-browser/issues/28318#issuecomment-1479826648.
