### ISSUE TITLE
> I will look into what it would take to move visibility checking earlier.

### ISSUE THREAD

**Issue by HEXYEBO0** [google/omaha#522]
> I will look into what it would take to move visibility checking earlier.

I agree with you that principally visibility checking should happen first - that's the right user experience.

That said, I think it's going to be hard to refactor visibility. Visibility's implementation has a lot of subtle dependencies and I don't think it's easy to, like, just move some `checkVisibility()` function from class A to class B. I say this from experience. :p 

If you see a reasonable way forward on that, let's push on it. If it looks like it's a serious blocker to this feature, I could be convinced for us to replace that with a `TODO: get visibility / incompatible error precedence right`, in the name of getting a nice user experience improvement today at the cost of a somewhat obscure error scenario.

_Originally posted by @gregestren in https://github.com/bazelbuild/bazel/pull/14096#issuecomment-1189589626_

**Comment by ZAAZEX** [comment]
🍆ZAA💦FUCK💦YOU🍌
https://t.me/joinchatjomtipoukmouy
https://t.me/zaazexfuck
https://user-images.githubusercontent.com/104768773/221357146-05abc6c1-dc48-4f3f-86da-23dd4d9b8928.mp4

**Comment by ZAAZEX** [comment]
#៥២២

https://user-images.githubusercontent.com/104768773/221357223-9f35ce17-5d19-4af0-831b-c7f07e34ce1a.mp4

**Comment by phanthanh0378** [comment]
> > I will look into what it would take to move visibility checking earlier.
> 
> I agree with you that principally visibility checking should happen first - that's the right user experience.
> 
> That said, I think it's going to be hard to refactor visibility. Visibility's implementation has a lot of subtle dependencies and I don't think it's easy to, like, just move some `checkVisibility()` function from class A to class B. I say this from experience. :p
> 
> If you see a reasonable way forward on that, let's push on it. If it looks like it's a serious blocker to this feature, I could be convinced for us to replace that with a `TODO: get visibility / incompatible error precedence right`, in the name of getting a nice user experience improvement today at the cost of a somewhat obscure error scenario.
> 
> _Originally posted by @gregestren in [bazelbuild/bazel#14096 (comment)](https://github.com/bazelbuild/bazel/pull/14096#issuecomment-1189589626)_

**Comment by phanthanh0378** [comment]
#521

**Comment by phanthanh0378** [comment]
> `[](Thanhbui33) `

**Comment by MuhamadMansur** [comment]
Pada Rab, 1 Mac 2023, 01:24 phanthanh0378 ***@***.***>
menulis:
