### ISSUE TITLE
Bugjaeger app

### ISSUE THREAD

**Issue by zinnakhan** [google/omaha#569]
I like this app

https://play.google.com/store/apps/details?id=eu.sisik.hackendebug

**Comment by 1983Thai** [comment]
I will try to learn and consider the problems to develop

**Comment by Arezoomohammadalizadeh** [comment]
Sent from my iPhoneOn May 21, 2023, at 10:18, THAI SANTDART CO.,LTD ***@***.***> wrote:﻿
I will try to learn and consider the problems to develop

**Comment by 1983Thai** [comment]
I will try to learn and consider the problems to develop
