### ISSUE TITLE
IsVistaOrLater() tests only the major version

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/omaha#59]
```
Calling ::VerifyVersionInfo() to test for major version must also include 
minor, SP major and SP minor
See MSDN 
http://msdn.microsoft.com/en-us/library/windows/desktop/ms725492%28v=vs.85%29.as
px

This is implemented in 
omaha\base\vistautil.cc

```

Original issue reported on code.google.com by `nir....@panel-sw.co.il` on 6 Jan 2014 at 5:22

**Comment by GitHubGanesh** [comment]
Thank you for reporting. What we are going to do is use the ::IsWindowsVistaOrGreater() versionhelpers function, and eliminate this function.
