### ISSUE TITLE
Patch for /trunk/clickonce/clickonce_bootstrap.cs

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/omaha#63]
```
Simplified ProcessStartInfo creation.
```

Original issue reported on code.google.com by `jernej.n...@gmail.com` on 14 Apr 2014 at 7:37

Attachments:
* [clickonce_bootstrap.cs.patch](https://storage.googleapis.com/google-code-attachments/omaha/issue-63/comment-0/clickonce_bootstrap.cs.patch)

**Comment by GitHubGanesh** [comment]
This does not work with the version of the compiler we are using:

        ProcessStartInfo psi = new ProcessStartInfo {
          FileName = setup_path,
          Verb = "open",
          Arguments = String.Format("/installsource clickonce /install \"{0}\"", query_string),
        };

Microsoft (R) Visual C# 2005 Compiler version 8.00.50727.1434
for Microsoft (R) Windows (R) 2005 Framework version 2.0.50727
Copyright (C) Microsoft Corporation 2001-2005. All rights reserved.

clickonce\clickonce_bootstrap.cs(70,53): error CS1526: A new expression requires
       () or [] after type
