### ISSUE TITLE
Why does GoogleUpdateComRegisterShell64.exe not have a manifest?

### ISSUE THREAD

**Issue by mherrmann** [google/omaha#649]
We're running into the problem that our equivalent of this file (and another one, for Arm64) gets blocked by Windows. (To be specific, we noticed the problem on Arm64 Windows 11.) Adding the `run_as_invoker.manifest` fixes the problem. Is there a reason why it (or a similar manifest) wasn't attached to the file in the first place?

**Comment by Ranabilal72** [comment]
Hello I would like to know about this app github I don't know anything
about this app for what purpose it is used

**Comment by WilliamAaron** [comment]
Yes, I am aware they have the wrong idea here they think I’ve committed
fraud I’m on disability and I have been for 20 years cause I broke my neck
and I don’t know why they chose this exact moment, but this is about
enough. I am getting a lawyer on it I mean I don’t know what else to do.
I’ve been harassed for the past couple weeks And that’s cyber bullying no
matter which way it goes and I am the victim here if you have any doubt
well all you gotta do is ask for proof and I’ll see what I can do to get it
to you cause my little sister is a lawyer a big sister is a doctor and
they’ll testify that yeah  And well I don’t know what’s going on in America
but it’s very very uncool right now and well y’all are I’m sure you can
find somewhere on y’all‘s database searching for my records. Yes, I barely
survived. It took me four years to walk again cause I got no therapy
whatsoever now make your own decisions. I understand. I’m a little
disappointed but I’m not mad and not listening either whatever my mom died
last weekend and in Granbury Texas yes but if you need somebody to contact
you, I will get them to and let them tell you exactly what’s going on thing
is nobody’s talk to me directly yet they only gave me an interview over the
Internet  not very nice one too like I said 20 years ago actually it was in
2002 that I broke my neck three vertebrae got removed so yeah try to say
I’m not disabled after that yes I can walk but it took four years to do it
again to get a mile  yeah they can’t say I’m not disabled. I don’t know
what they is probably the same thing it’s been over all the years they just
don’t care and with all the stuff going on at the border right now they
pick a heckuva time to pull this on me make up your mind y’all are y’all
are the information  system for the world, so check it from there

null

**Comment by mherrmann** [comment]
Hi @sorinj, I understand there's a lot of spam above; But has this really been fixed?

**Comment by sorinj** [comment]
it has not, I made a mistake closing the issue.

**Comment by sorinj** [comment]
Fixed by: https://github.com/google/omaha/commit/c3e428cce2af4f8619658b553292147643820219
