### ISSUE TITLE
failed to build gmock-all 

### ISSUE THREAD

**Issue by universeroc** [google/omaha#73]
=== settings of environments ====
call hammer.bat

gmock-all.cc
E:\omaha\third_party\gmock\include\gmock/internal/gmock-generated-internal-utils.h(72): error C2039: 'tuple': is not a member of 'testing'
E:\omaha\third_party\gmock\include\gmock/internal/gmock-generated-internal-utils.h(46): note: see declaration of 'testing'
E:\omaha\third_party\gmock\include\gmock/internal/gmock-generated-internal-utils.h(72): error C2065: 'tuple': undeclared identifier
E:\omaha\third_party\gmock\include\gmock/internal/gmock-generated-internal-utils.h(72): error C2059: syntax error: '>'
E:\omaha\third_party\gmock\include\gmock/internal/gmock-generated-internal-utils.h(72): error C2976: 'testing::internal::MatcherTuple': too few template arguments
E:\omaha\third_party\gmock\include\gmock/internal/gmock-generated-internal-utils.h(69): note: see declaration of 'testing::internal::MatcherTuple'
E:\omaha\third_party\gmock\include\gmock/internal/gmock-generated-internal-utils.h(72): error C2988: unrecognizable template declaration/definition
E:\omaha\third_party\gmock\include\gmock/internal/gmock-generated-internal-utils.h(72): error C2143: syntax error: missing ';' before '>'
E:\omaha\third_party\gmock\include\gmock/internal/gmock-generated-internal-utils.h(72): error C2913: explicit specialization; 'testing::internal::MatcherTuple' is not 

Then I pass --msvs to hammer.bat like:
call hammer.bat --msvs

It does not generate visual stuido sln project file and also show me those errors again
How to make these procedure work correctly ?
Could somebody tell me why? Thank you in advance. :)

**Comment by universeroc** [comment]
This is content of my build.bat'

@echo off

set VSINSTALLDIR=C:/Program Files (x86)/Microsoft Visual Studio 14.0/
set ATLMFC_VC14_0_DIR=C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/atlmfc
set OMAHA_PLATFORM_SDK_DIR=C:/Program Files (x86)/Windows Kits/10v
set OMAHA_NETFX_TOOLS_DIR=C:/Program Files (x86)/Microsoft SDKs/Windows/v10.0A/bin/NETFX 4.6 Tools
set OMAHA_SIGNTOOL_SDK_DIR=C:/Program Files (x86)/Windows Kits/10/bin/x86
set OMAHA_WIX_DIR=C:/Program Files (x86)/WiX Toolset v3.8/bin
set SCT_DIR=C:/SWTOOLKIT
set VCINSTALLDIR=C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/
set VisualStudioVersion=14.0
set WindowsSdkDir=C:/Program Files (x86)/Windows Kits/10
set OMAHA_PYTHON_DIR=C:/Python24

set WindowsSDKVersion=10.0.10240.0/
set GOROOT=C:/Program Files (x86)/Go/files
set PATH=%PATH%;C:/Python24;C:/Program Files (x86)/Microsoft SDKs/Windows/v10.0A/bin/NETFX 4.6 Tools

cd omaha/omaha

:: build
call hammer.bat --msvs & cd %~dp0

**Comment by sorinj** [comment]
My thinking is that somehow the build script is not including the headers for VC14 but some other set of headers. Can you please run "hammer --verbose" ? That will output the command line the compiler is invoked with.

Also, are you calling the correct vcvarsall.bat script before invoking hammer in that command shell?

I debug similar environment issues by add a line of code to main.scons around L903 https://github.com/google/omaha/blob/master/omaha/main.scons#L903:

print windows_debug_env.Dump()

That line of code dumps the build environment. Look for the INCLUDE section, to see what is the INCLUDE path for the build. In my case, it looks like this:


  'ENV': { 'COMSPEC': 'C:\\Windows\\system32\\cmd.exe',
           'GOROOT': 'C:\\Program Files (x86)\\go\\files',
           'INCLUDE': 'C:\\Program Files (x86)\\Windows Kits\\10\\\\include;C:\\Program Files (x86)\\Microsoft Visual St
udio 14.0\\vc\\include;C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.10240.0\\um;C:\\Program Files (x86)\\Win
dows Kits\\10\\include\\10.0.10240.0\\shared;C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.10240.0\\ucrt;C:\\
Program Files (x86)\\Microsoft Visual Studio 14.0\\vc\\atlmfc\\include',
           'LIB': 'C:\\Program Files (x86)\\Windows Kits\\10\\\\lib;C:\\Program Files (x86)\\Microsoft Visual Studio 14.
0\\vc\\lib;C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.10240.0\\um\\x86;C:\\Program Files (x86)\\Windows Kits\\
10\\lib\\10.0.10240.0\\ucrt\\x86;C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\vc\\atlmfc\\lib',
           'LIBPATH': 'C:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319;C:\\Windows\\Microsoft.NET\\Framework\\v3.5;c:\
\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\LIB;c:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\A
TLMFC\\LIB',
           'PATH': 'C:\\Program Files (x86)\\Windows Kits\\10\\\\bin;C:\\Program Files (x86)\\Microsoft Visual Studio 14
.0\\vc\\bin;C:\\Program Files (x86)\\Windows Kits\\10\\\\\\bin\\x86;C:\\Program Files (x86)\\Microsoft SDKs\\Windows\\v1
0.0A\\bin\\NETFX 4.6 Tools\\;C:\\Python24;C:\\Windows\\Microsoft.NET\\Framework\\v2.0.50727;C:\\Program Files (x86)\\WiX
 Toolset v3.8\\bin',

**Comment by universeroc** [comment]
@sorinj Thank you for your reply. And I follow your advice to do print these things and here it is:

scons: Building targets ...
scons: building associated VariantDir targets: scons-out
cl /Foscons-out\dbg-win\obj\third_party\gmock\src\gmock-all.obj /c E:\omaha\third_party\gmock\src\gmock-all.cc /TP /nologo /c /Zc:forScope /D_HAS_EXCEPTIONS=0 /DCOMPILER_MSVC /DSTL_MSVC /GR- /D_CRT_SECURE_CPP_OVERLOAD_SECURE_NAMES=1 /D_CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES=1 /D_CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_COUNT=1 /D_CRT_RAND_S /WX /d2Zi+ /wd4061 /wd4127 /wd4189 /wd4505 /wd4191 /wd4217 /wd4365 /wd4371 /wd4510 /wd4512 /wd4514 /wd4555 /wd4610 /wd4619 /wd4623 /wd4625 /wd4626 /wd4668 /wd4710 /wd4711 /wd4738 /wd4755 /wd4777 /wd4820 /wd4987 /wd4995 /wd4996 /wd28159 /wd28204 /wd28251 /FS /Od /RTC1 /MTd /wd4061 /wd4242 /wd4244 /wd4628 /wd4640 /wd4826 /W4 /Wall /FIE:\omaha\omaha/precompile/precompile.h /DPSAPI_VERSION=1 /DWINVER=0X0500 /DWIN32 /D_WINDOWS /DUNICODE /D_UNICODE /DWIN32_LEAN_AND_MEAN /DSTRICT /DSECURITY_WIN32 /D_ATL_ALL_WARNINGS /D_ATL_CSTRING_EXPLICIT_CONSTRUCTORS /D_ATL_CSTRING_NO_CRT /D_ATL_NO_ACLAPI /D_ATL_NO_DEFAULT_LIBS /D_ATL_NO_EXCEPTIONS /D_ATL_NO_GLOBAL_SOCKET_STARTUP /D_ATL_NO_PERF_SUPPORT /D_ATL_NO_TRACK_HEAP /D_ATL_NO_UUIDOF /D_ATL_STATIC_REGISTRY /D_ATL_XP_TARGETING /D_CRT_RAND_S /D_SECURE_ATL=1 /D_WTL_NO_CSTRING /DDNTDDI_VERSION=NTDDI_WINXPSP3 /DNOMINMAX /DLOGGING "/DFULL_COMPANY_NAME_ANSI=\"OmahaCompanyName Inc.\"" /DSHORT_COMPANY_NAME_ANSI=\"OmahaCompanyName\" /DPRODUCT_NAME_ANSI=\"Update\" /DCOMPANY_DOMAIN_BASE_ANSI=\"google\" /DCOMPANY_DOMAIN_ANSI=\"google.com\" "/DOMAHA_APP_NAME_ANSI=\"OmahaCompanyName Update\"" /DMAIN_EXE_BASE_NAME_ANSI=\"GoogleUpdate\" /DMAIN_DLL_BASE_NAME_ANSI=\"goopdate\" /DOFFICIAL_BUILD=0 /DTEST_CERTIFICATE=1 /DONECLICK_PLUGIN_NAME=_T(\"npGoogleOneClick\") /DONECLICK_PLUGIN_VERSION_ANSI=\"9\" /DONECLICK_PLUGIN_FILENAME=_T(\"npGoogleOneClick9.dll\") /DUPDATE_PLUGIN_NAME=_T(\"npGoogleUpdate\") /DUPDATE_PLUGIN_VERSION_ANSI=\"3\" /DUPDATE_PLUGIN_FILENAME=_T(\"npGoogleUpdate3.dll\") /DBHO_NAME=_T(\"GoopdateBho\") /DBHO_FILENAME=_T(\"GoopdateBho.dll\") /DCRASH_HANDLER_NAME=_T(\"GoogleCrashHandler\") /DARCH_CPU_X86_FAMILY "/DPROXY_CLSID_IS_MACHINE={0x530D5B5E, 0x93F7, 0x4A83, {0x8E, 0xC4, 0x50, 0x5B, 0x56, 0xE6, 0x98, 0x89}}" "/DPROXY_CLSID_IS_USER={0xAC86AA17, 0x35D1, 0x414E, {0x99, 0x1A, 0x74, 0xEB, 0x4F, 0x30, 0x6A, 0x25}}" /D_DEBUG /DDEBUG /D_LIB /IC:\atl_server\files\include /IC:\wtl\files\include /IE:\omaha /I. /Ithird_party\chrome\files\src /IE:\omaha\third_party\breakpad\src /IE:\omaha\third_party\gmock /IE:\omaha\third_party\gmock\include /IE:\omaha\third_party\gtest\include /YuE:\omaha\omaha/precompile/precompile.h /Fpscons-out\dbg-win\obj\third_party\gmock_pch.pch /Z7
gmock-all.cc
E:\omaha\third_party\gmock\include\gmock/internal/gmock-internal-utils.h(45) : fatal error C1083: Cannot open include file: 'gmock/internal/gmock-generated-internal-utils.h': No such file or directory
scons: building terminated because of errors.

You know there also are the very includes. And I found another thing was that inside gmock or gtest there are also gmock.sln and gtest.sln. BUT they also could not be compiled successfully and have the same errors as above.

Could you compile it sucessfully @sorinj ?

**Comment by sorinj** [comment]
I apologize for the late answer. I subscribed to notifications to all conversations but the email went past my gmail filters and I missed it.

I think I know where the problem could be, I am looking into this.

**Comment by sorinj** [comment]
Can you please try again? 

Before you do that, please use googletest from https://github.com/google/googletest instead of the old gtest and gmock from code.google.com.

**Comment by universeroc** [comment]
@sorinj sorry for late reply. I'll try your solution :+1:
