### ISSUE TITLE
TimeTest.TimeToStringTest is broken on VS2015

### ISSUE THREAD

**Issue by sorinj** [google/omaha#74]
The underlying issue here is that the implementation of ATL's CTime has changed in the Windows 10 SDK. CTime is used as expected result by the unit test, therefore, the test fails due to TZ issues.

[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from TimeTest
[ RUN      ] TimeTest.TimeToStringTest
base\time_unittest.cc(85): error: Value of: date2
  Actual: L"Thu, 12 Nov 2015 17:45:06 GMT"
Expected: date1
Which is: L"Thu, 12 Nov 2015 16:45:06 GMT"
base\time_unittest.cc(85): error: Value of: date2
  Actual: L"Thu, 10 Dec 2015 17:45:06 GMT"
Expected: date1
Which is: L"Thu, 10 Dec 2015 16:45:06 GMT"
base\time_unittest.cc(85): error: Value of: date2
  Actual: L"Thu, 07 Jan 2016 17:45:06 GMT"
Expected: date1
Which is: L"Thu, 07 Jan 2016 16:45:06 GMT"
base\time_unittest.cc(85): error: Value of: date2
  Actual: L"Thu, 04 Feb 2016 17:45:06 GMT"
Expected: date1
Which is: L"Thu, 04 Feb 2016 16:45:06 GMT"
base\time_unittest.cc(85): error: Value of: date2
  Actual: L"Thu, 03 Mar 2016 17:45:06 GMT"
Expected: date1
Which is: L"Thu, 03 Mar 2016 16:45:06 GMT"
[  FAILED  ] TimeTest.TimeToStringTest (15 ms)
[----------] 1 test from TimeTest (18 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (26 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] TimeTest.TimeToStringTest

**Comment by Suradach** [comment]
On issue
