### ISSUE TITLE
Fix build break

### ISSUE THREAD

**Issue by sorinj** [google/omaha#76]
The build is broken due to https://chromium.googlesource.com/breakpad/breakpad/+/cf1087c403de8d496f3f2a919327edaa30385731

goopdate\crash.cc(263): error C2664: 'google_breakpad::ReportResult google_breakpad::CrashReportSender::SendCrashReport(
const std::wstring &,const std::map<std::wstring,std::wstring,std::less<_Kty>,std::allocator<std::pair<const _Kty,_Ty>>>
 &,const std::map<_Kty,_Ty,std::less<_Ty>,std::allocator<std::pair<const _Kty,_Ty>>> &,std::wstring *)': cannot convert
argument 3 from 'const wchar_t *' to 'const std::map<std::wstring,std::wstring,std::less<_Kty>,std::allocator<std::pair<
const _Kty,_Ty>>> &'
        with
        [
            _Kty=std::wstring,
            _Ty=std::wstring
        ]
goopdate\crash.cc(263): note: Reason: cannot convert from 'const wchar_t *' to 'const std::map<std::wstring,std::wstring
,std::less<_Kty>,std::allocator<std::pair<const _Kty,_Ty>>>'
        with
        [
            _Kty=std::wstring,
            _Ty=std::wstring
        ]
goopdate\crash.cc(263): note: No constructor could take the source type, or constructor overload resolution was ambiguou
s

**Comment by universeroc** [comment]
when to fix this problem ?

**Comment by sorinj** [comment]
This should be fixed by 7d2e458ee5a305af3aac7649e3749d44d4b98207
