### ISSUE TITLE
Does not build with VS2015, 2013 or 2012

### ISSUE THREAD

**Issue by thehumanfallacy** [google/omaha#82]
Hello,

I believe I've followed all the instructions properly on the developer setup page but am having issues building with VS2015, 2013 or 2012.  The problem seems to me that SCons 1.3.1 can't detect any of my installed versions of Visual Studio even though I have 2012 through 2015 installed.  The first error messages printed are:
```
scons: warning: No installed VCs
scons: warning: No version of Visual Studio compiler found - C/C++ compilers most likely not set correctly
File "...\omaha\omaha\tools\proxy_clsid_utils.py", line 47, in _GenerateGuid
    raise SystemError("Failed to get GUID: %s" % guid)
SystemError: Failed to get GUID: 'uuidgen.exe' is not recognized as an internal or external command,
```

So it's failing to find the tools it needs and dies.  After finding where the first message is printed in C:\Python24\Lib\site-packages\scons-1.3.1\SCons\Tool\MSCommon\vc.py I can see that the _VCVER table is actually: 
```
_VCVER = ["10.0", "9.0", "9.0Exp","8.0", "8.0Exp","7.1", "7.0", "6.0"]
```

VS2012 is version 11.0 so this table ends at 2010.  Also, if I type ```uuidgen.exe /c``` manually in the same shell I tried running hammer in it gives me a valid GUID.  This implies to me that something on the developer setup page might be inaccurate, such as versions of tools that are needed.

Can someone please confirm that the setup page is dead on as written?  Thanks.

    Drew

**Comment by thehumanfallacy** [comment]
This particular problem turned out to be a mistake with the paths I had set up in hammer.bat.

**Comment by jplethier** [comment]
@thehumanfallacy which path was wrong? I am having the same issue here, but I did not discover what path to fix, I already tried some changes but the error remaining. :(

**Comment by Montesdodgers13** [comment]
Which path is wrong I been trying too figure out

**Comment by thehumanfallacy** [comment]
I'm sorry but I don't actually recall what I had done wrong. We ended up writing our own updater in the end. I'm sure Omaha works wonderfully once you have it configured properly but to use it correctly you need to change all of those GUIDs and that is very hard to get right. I think someone needs to spend some time making the project more configurable.

**Comment by thehumanfallacy** [comment]
Also, it's possible it might be more configurable now, I haven't checked it out in a long time.

**Comment by AMartens181** [comment]
Does it build with VS2017?
