### ISSUE TITLE
np_entry.cc may occur an error in windows

### ISSUE THREAD

**Issue by cnssay** [google/omaha#84]
I just found that there are several special characters, which may result in errors from vs2013 in the np_entry.cc file. 
These characters appear in line 237, 275 and 266. Are these spelling mistake?
Now, the only solution is to delete them.

**Comment by ullerrm** [comment]
That code is #ifdef'd out on all Omaha builds, and can be safely ignored for now.  (Also, it's in comments.)

Look at the entire file, and you'll notice that it's boilerplate code from Netscape with two implementations inside it -- one for Windows (lines 49-165), and one for Mac (lines 205-320).  The special characters are part of the Mac-only code, and appear as normal text when viewed using a MacRoman encoding.

**Comment by Chuan-Ru** [comment]
?

2016-04-12 2:30 GMT+08:00 Ryan <notifications@github.com>:
