### ISSUE TITLE
Folder 'official' missing

### ISSUE THREAD

**Issue by ulabs-sgiroux** [google/omaha#86]
In paragraph 2 of the 'customizing omaha' document (https://github.com/google/omaha/blob/116c23e551175e0c240d895941df7f682cfc41d1/CustomizingOmaha.md) there is mention of an 'official' directory containing files with original CLSIDs and other customizable aspects.

This is missing in the latest codebase https://github.com/google/omaha/tree/b8670ff3034e80e20a5bde76379c112564a2cb58

It may be useful to folks who want to test with `is_google_update_build` set to true

**Comment by sig0519** [comment]
is_google_updated
