### ISSUE TITLE
Question regarding certificate_tag.go and apply_tag.cc

### ISSUE THREAD

**Issue by tomwolfgang** [google/omaha#87]
Do they both do the same thing? Are they implementing the same trick?

Thanks

**Comment by sorinj** [comment]
Yes, they have similar functionality. 

certificate_tag.go is newer code and it was developed with the intention of reuse for the server side implementations of Omaha supporting infrastructure, which in some cases it is written in Go.

**Comment by tomwolfgang** [comment]
A quick look at certificate_tag.go - looks like it is portable? (specifically Linux).

One more thing - README contains: More details are here: http://b/12236017 - can you post the fulll link please?

Thanks again!

**Comment by sorinj** [comment]
The full link points to a system not publicly accessible. The context for the changes is this: https://technet.microsoft.com/library/security/2915720

In summary, Omaha injects some untrusted metadata in its metainstallers at download time in such a way that the Authenticode signature of the binary is not tampered. Microsoft changed to way Authenticode validation worked, and so, Omaha had to change its code too.

**Comment by chaubunhtha** [comment]
Chào
