### ISSUE TITLE
Not backward compatible Omaha managed Client Software

### ISSUE THREAD

**Issue by xDrFred** [google/omaha#88]
Hey all

We want to use the google omaha software updater for our products. For the server part we use the Crystalnix/omaha implementation.

As far as I understood are the scheduled tasks the only part where update requests are sent once the application has been installed with a taged meta installer. (I do not know mutch about the services yet (omaha, omaham))

Now we want to call update requests manually when the client software detects that an update is available. As the software is installed with the "needsadmin=True" flag which means administrator privileges are required to update it. The software itself doesn't run with administrator privileges.

As I can't call the scheduled tasks according to the missing rights I need an other way to invoke an update. Does this update software eaven support such an action?

Is it a good idea to hack around omaha to implement an non backward compatible client software?

**Comment by sorinj** [comment]
On Wed, Jun 22, 2016 at 12:14 PM, xDrFred <notifications@github.com> wrote:

> Hey all
>
> We want to use the google omaha software updater for our products. For the
> server part we use the Crystalnix/omaha implementation.
>
> As far as I understood are the scheduled tasks the only part where update
> requests are sent once the application has been installed with a taged meta
> installer. (I do not know mutch about the services yet (omaha, omaham))
>
The Omaha client follows a client-server design, where the scheduled task
acts as a client to drive another part of Omaha, the server, which provides
the code for the actual downloading and installing of updates. The server
code runs as a Windows service, if Omaha is installed per-system aka
per-machine. omaham is a service broker which exposes a locked down API to
omaha.

> Now we want to call update requests manually when the client software
> detects that an update is available. As the software is installed with the
> "needsadmin=True" flag which means administrator privileges are required to
> update it. The software itself doesn't run with administrator privileges.
>
This seems similar to the case of updating Google Chrome, when Chrome is
installed per-system.

> As I can't call the scheduled tasks according to the missing rights I need
> an other way to invoke an update.
>
 I suggest taking a look at how Chrome calls into Omaha using
IGoogleUpdate3Web to trigger what we call a manual update:
https://cs.chromium.org/chromium/src/chrome/browser/google/google_update_win.h?q=IGoogleUpdate3Web&sq=package:chromium&dr=C

Does this update software eaven support such an action?
>
It does, assuming I've understood the problem we are trying to solve.

**Comment by xDrFred** [comment]
Sorry for the late response
Thanks for the information it was exactly what I was searching for.
With the help of the COM components I wrote a .NET Library which does basically the same as the UpdateCheckDriver::RunUpdateCheck method

**Comment by q71114** [comment]
@NtFreX Can you share your .NET Library or just an overview on what is needed to be done in order to achieve manual update with Omaha? It would greatly help us who are investigating Omaha to be their update framework.

**Comment by NtFreX** [comment]
@q71114 I've uploaded a small library which contains the code to update an application with omaha. It also gives you the possibility to upload exception dumps and  feedbacks to the [crystalnix/omaha-server](https://github.com/Crystalnix/omaha-server).
The repo is [NtFreX/OmahaClientSdk](https://github.com/NtFreX/OmahaClientSdk). I need to clean it up but it is working. Updating the current application without knowing the identifier isn't implemented yet.

**Comment by q71114** [comment]
Thank you. I will check it out.

**Comment by KJandSB** [comment]
idk wtf this is¿?

Miss Kelly Josephine
