### ISSUE TITLE
The unofficial setup guide is now chargeable

### ISSUE THREAD

**Issue by xDrFred** [google/omaha#97]
Does this match the site philosophy? 
Feel free to delete this issue if you dont bother

**Comment by Elghandour1022** [comment]
table.main {width: 94% !important;display: block; margin: 0 auto;}
body {margin: 0;background: #f7f7f7;}
div.background {width: 100%; padding: 0!important;}
div.wrapper {padding: 15px 0 3px!important;}
td.header {padding-top:10px!important;}
td.header td.kind {padding: 0px 10px 0 0!important; vertical-align: top;}
td.header td.kind img {width: 40px; height: 40px;}
td.header .logo {padding-top: 19px;}
table.main td.sub { padding: 7px 0 13px!important; }
table.main td.kind {text-align: right;}
td.footer {height: 100%!important; padding:0.6em 0!important;}
td.footer p {font-size:12px!important; line-height:1.4em!important; margin: 0!important; }
table.inner {width: 100%!important;}
table.main .comment_wrap {padding: 15px 0 12px !important;}
table.main .comment_wrap.first {padding: 0 0 12px !important;}
table.main td.coub-pic {padding-top: 0 !important;}
div.lefter { width: 100%; margin-right: 0!important; }
div.lefter td.coub-pic {padding-bottom: 7px!important; width: 140px;}
table.main .coub-pic a {min-height: 100% !important;}
div.lefter td.coub-pic img {margin: 0 auto;}
table.main td.user-count {line-height: 12px; width: 30px !important; padding: 4px 6px 0 0 !important;}
table.main td.user-count img {width: 30px; height: 30px;}
table.main td.total-num a {font: bold 16px/17px Arial, Helvetica, sans-serif; padding: 6px !important;}
table.main .group-header {position: absolute; right: 15px; top: 15px;}
table.main .notification-group .wrapper {position: relative;}
table.main table.users {margin-top: 3px !important;}
td.left table {width: 100% !important;}
table.new_follower.main .righter, .new_follower.notification-group .righter {width: 60% !important;-premailer-width: 60% !important;}
table.new_follower.main td.name, .new_follower.notification-group td.name {font-size: 13px !important; padding-top: 0 !important;position: relative; top: -2px;}
table.new_follower.main td.kind, .new_follower.notification-group td.kind {width: 40px !important;}
table.new_follower.main .wrapper, .new_follower.notification-group .wrapper {padding: 15px 15px 3px !important}
table.new_follower.main td.followers, table.invite_email.main td.followers, table.new_like.main td.followers, .new_follower td.followers {padding: 7px 20px;text-align: left !important;}
table.new_follower.main .pic, .new_follower.notification-group .pic {width: 60px !important;}
table.new_follower.main .pic img, .new_follower.notification-group .pic img {width: 60px !important; height: 60px !important;}
table.new_follower.main td.follower-pic, table.invite_email.main td.follower-pic, table.new_like.main td.follower-pic, .new_follower td.follower-pic {padding-top: 0 !important;}
table.editor_reminder.main .comment_wrap {width: 90% !important; margin: 0 auto; display: block; padding: 0 0 12px !important;}
table.editor_reminder.main .righter {width: 100% !important;padding-top: 7px;}
table.editor_reminder.main .righter .inner {width: 100% !important; display: block;}
table.editor_reminder.main .righter .make-coub {width: 100% !important; display: block; text-align: center !important; padding-top: 0 !important;}
table.editor_reminder.main p.reminderTitle {margin: 0 0 12px 0 !important;}
table.editor_reminder.main p.reminderFrom {padding: 0 0 16px 0 !important;font-size: 14px !important;}
table.editor_reminder.main .lefter > table {width: 100% !important;}
table.editor_reminder.main .lefter .coub-pic {padding-bottom: 12px;}
table.editor_reminder.main .righter > table {width: 100% !important;}
table.editor_reminder.main .righter .inner {text-align: center;}
table.editor_reminder.main .lefter {padding-top: 5px;}
table.copyright_ban_mail.main .righter .title, table.marked_18_mail.main .righter .title, table.banned_mail.main .righter .title {height: auto !important;}
table.copyright_ban_mail.main table.inner, table.marked_18_mail.main table.inner, table.banned_mail.main table.inner {margin: 0 auto; width: 89% !important;}
table.copyright_ban_mail.main td.kind, table.marked_18_mail.main td.kind, table.banned_mail.main td.kind {width: 40px !important; padding-top: 0 !important;position: relative;right: -2px;}
table.copyright_ban_mail.main .righter, table.marked_18_mail.main .righter, table.banned_mail.main .righter {width: 100% !important; -premailer-width: 100% !important;}
table.copyright_ban_mail.main .lefter td.coub-pic, table.marked_18_mail.main .lefter td.coub-pic, table.banned_mail.main .lefter td.coub-pic {padding-bottom: 13px !important;}
table.copyright_ban_mail.main .comment_wrap, table.marked_18_mail.main .comment_wrap, table.banned_mail.main .comment_wrap {padding: 0 0 12px !important;}
table.copyright_ban_mail.main td.kind {position: relative; right: -3px;}
table.new_category.main .comment-wrap-i{width: 100% !important;}
tr.new_category.notification-group .comment_wrap, table.new_category .comment_wrap {padding: 0 0 12px !important;}
table.digest_mail.main .new_category .section.first, table.new_category .section.first {padding: 0 15px !important;}
table.new_follower.main .righter td.followers .count, tr.new_follower table td.followers .count {font-size: 10px !important;}
table.new_follower.main .righter td.followers, tr.new_follower table td.followers {font-size: 10px !important;}
table.invite_email.main .followers .count, tr.new_follower table .followers .count {font-size: 10px !important;}
table.invite_email.main .followers, tr.new_follower table .followers {font-size: 10px !important;}
table.verify_email.main .inner table {width: 90% !important; margin: 0 auto; display: block;}
table.new_like.main .comment-wrap-i, table.new_recoub.main .comment-wrap-i {width: 90% !important; -premailer-width: 90% !important;position: relative;}
table.new_like.main table.inner, table.new_recoub.main table.inner {width: 100% !important;-premailer-width: 100% !important;}
table.new_like.main .kind, table.new_recoub.main .kind {position: absolute; top: 0; right: 0;}
table.new_like.main .kind {top: -5px !important;}
table.new_recoub.main .kind {right: -5px !important;}
table.new_like.main .righter, table.new_category .righter, table.new_recoub.main .righter {width: 90% !important;-premailer-width: 90% !important;}
table.new_like.main .comment_wrap .inner-comments, table.new_recoub.main .comment_wrap .inner-comments {width: 100% !important;}
td.verify-logo {height:100%; padding-bottom: 20px!important;}
td.verify-logo img {width: 260px; height: 50px;}
table.invite_email.main td.invite_section > table{width: 100% !important;}
table.invite_email.main  .random_coubs .section > table{width: 100% !important; margin: 0 !important;}
table.invite_email.main  .random_coubs {padding: 0 15px;}
table.invite_email.main  .left {display: block; width: 80% !important; padding: 0 15px;}
table.invite_email.main  .mail-desc {width: 90%; margin: 0 auto; display: block; padding: 15px 0 0 !important; }
table.invite_email.main  .mail-desc > table {width: 100% !important; display: block;}
table.cotd_mail.main td.sub.cotd_mail {display:block; margin: 0 30px!important; padding: 0 0 23px !important; font-size: 15px !important; line-height: 21px !important;}
table.cotd_mail.specific {margin-top: 10px;}
table.cotd_mail.main td.coub-pic { padding: 5px 0 10px!important;}
table.cotd_mail.main .outer { padding-bottom: 0!important; }
table.cotd_mail.main .footer { border-color: rgba(0,0,0,0.1); }
td.cotd-logo {height: 75px;}
td.cotd-logo img {width: 227px; height: 46px;}
table.cotd_mail.main .bottom-logo {padding: 234px 6px 20px 0 !important;}
table.digest_mail.main .new_category .wrapper {padding: 0 0 3px !important;}
table.digest_mail.main .new_category .comment-wrap-i {width: 90% !important;}
table.digest_mail.main .new_category .section {padding: 15px 0 0 !important;}
table.digest_mail.main .new_category .section.first {padding: 15px 0 0 !important;}
div.digest .notification-group .group-header .content {width: 120px;text-align: right;}
div.digest .notification-group .group-footer td {padding: 8px 0 7px;}
div.digest .notification-group .group-body .list-item {padding: 0 !important;}
table .group-body .list-item > table {width: 90% !important;}
table.new_follower div.lefter, .new_follower.notification-group div.lefter {width: 60px; padding-right: 10px;}
table.new_follower td.followers, .new_follower.notification-group td.followers {padding: 7px 0 !important;}
table.new_follower .comment_wrap, .new_follower.notification-group .comment_wrap {padding: 0px 0 17px !important;}
table.digest_mail.main .new_follower .comment_wrap {width: 100%;}
table.reset_password.main div.wrapper, table.create_password.main div.wrapper {padding-top: 4px !important;}
table.reset_password.main td.reset-desc, table.create_password.main td.reset-desc {padding: 0 20px !important;}












Hey!





























ossama ghandour has invited you to join Coub




You should join Coub, it's awesome!






Reject
 
Accept invite




















Do not reply to this email; it was sent from an unmonitored address. For support, contact support@coub.com.
